from bot.keyboards.reply import (
    get_branch_keyboard,
    get_cancel_keyboard,
    get_citizenship_keyboard,
    get_experience_keyboard,
    get_interview_keyboard,
    get_language_keyboard,
    get_main_menu,
    get_metro_keyboard,
    get_phone_keyboard,
    get_skip_cancel_keyboard,
    remove_keyboard,
)
from bot.keyboards.inline import (
    get_hr_action_keyboard,
    get_hr_hold_keyboard,
    get_metro_lines_keyboard,
    get_metro_stations_keyboard,
    get_post_interview_keyboard,
    get_readiness_inline_keyboard,
    get_score_keyboard,
)
from bot.keyboards.inline_form import (
    get_confirmation_keyboard,
    get_evening_shifts_keyboard,
    get_experience_yn_keyboard,
    get_gender_keyboard,
    get_languages_keyboard,
    get_med_book_keyboard,
    get_positions_keyboard,
    get_schedule_keyboard,
    get_smoking_keyboard,
    get_weekends_keyboard,
)

__all__ = [
    # Reply keyboards (свободный ввод и главное меню)
    "get_branch_keyboard",
    "get_cancel_keyboard",
    "get_citizenship_keyboard",
    "get_experience_keyboard",
    "get_interview_keyboard",
    "get_language_keyboard",
    "get_main_menu",
    "get_metro_keyboard",
    "get_phone_keyboard",
    "get_skip_cancel_keyboard",
    "remove_keyboard",
    # Inline keyboards (HR и метро)
    "get_hr_action_keyboard",
    "get_hr_hold_keyboard",
    "get_metro_lines_keyboard",
    "get_metro_stations_keyboard",
    "get_post_interview_keyboard",
    "get_readiness_inline_keyboard",
    "get_score_keyboard",
    # Inline keyboards (форма анкеты)
    "get_confirmation_keyboard",
    "get_evening_shifts_keyboard",
    "get_experience_yn_keyboard",
    "get_gender_keyboard",
    "get_languages_keyboard",
    "get_med_book_keyboard",
    "get_positions_keyboard",
    "get_schedule_keyboard",
    "get_smoking_keyboard",
    "get_weekends_keyboard",
]
